# Generated by Django 4.1.7 on 2023-03-09 04:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('movies', models.JSONField()),
                ('created_by', models.IntegerField()),
                ('updated_by', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateField(blank=True, null=True)),
                ('is_active', models.IntegerField(default=1)),
                ('collection_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
