# Generated by Django 4.1.7 on 2023-03-09 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_counter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='counter',
            name='last_reset_by',
        ),
    ]
