# Generated by Django 4.1.7 on 2023-03-09 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_remove_counter_last_reset_by'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Counter',
        ),
    ]
